project:
  type: website
  output-dir: docs

website:
  title: "R/Medicine 2026"
  favicon: images/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Register.qmd
        text: Register
      - href: Submit.qmd
        text: Submit
      - href: Program.qmd
        text: Program
      # - href: Competition.qmd
      #   text: Competition
      - href: speaker_info.qmd
        text: Speaker guide
      # - href: keynotes26.qmd
      #   text: Keynotes
      - href: workshops.qmd
        text: Workshops
      - href: Hackathon.qmd
        text: Hackathon
      - href: Attend.qmd
        text: Code of Conduct
      - href: Committees.qmd
        text: Committees
      - href: Events.qmd
        text: Past Events
      - href: Contact.qmd
        text: Contact us
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    default-image-extension: svg
editor: source

execute:
  freeze: auto
